name: Continuous Integration for users-crud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: go mod download
    - name: Downloading updated tools for pact 
      run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | bash
    - name: Run contract test
      env:
        API: http://localhost:3001
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      run: go test -v ./test/contract/api